pipeline:
  build_docker:
    image: plugins/docker
    repo: andyet/facecamp-auth
    tags: 
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      event: deployment
  helm_deploy_prod:
    image: andyet/drone-helm:latest
    pull: true
    skip_tls_verify: false
    chart: ./charts/node-app
    prefix: PROD
    release: facecamp-auth
    values: secrets.data.CLIENT_SECRET=$${CLIENT_SECRET},secrets.data.CLIENT_ID=$${CLIENT_ID}
    secrets: [ PROD_CLIENT_SECRET, PROD_CLIENT_ID, PROD_KUBERNETES_CERTIFICATE, PROD_KUBERNETES_TOKEN, PROD_API_SERVER ]
    when:
      event: deployment
  slack:
    image: plugins/slack
    username: drone
    channel: alerts
    secrets: [ slack_webhook ]
