pipeline:
  build_docker:
    image: plugins/docker
    repo: andyet/facecamp-auth
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    secrets: [docker_username, docker_password]
    commands:
      - npm test
    when:
      event: deployment
  helm_deploy_prod:
    image: andyet/drone-helm:latest
    skip_tls_verify: false
    chart: andyet/node-app
    prefix: PROD
    recreate_pods: true
    helm_repos: andyet=https://andyet-helm-charts.storage.googleapis.com/
    release: facecamp-auth
    values: secrets.data.CLIENT_SECRET=$${CLIENT_SECRET},secrets.data.CLIENT_ID=$${CLIENT_ID}
    values_files: values.yaml
    secrets:
      - PROD_CLIENT_SECRET
      - PROD_CLIENT_ID
      - PROD_KUBERNETES_CERTIFICATE
      - PROD_KUBERNETES_TOKEN
      - PROD_API_SERVER
    when:
      event: deployment
  slack:
    image: andyet/drone-slack:stable
    username: drone
    pull: true
    channel: io-alerts
    secrets: [slack_webhook, github_access_token, github_slack_lookup]
    when:
      event: deployment
      status: [success, failure]
