apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
{{ toYaml .Values.ingress.annotations | trimSuffix "\n" | indent 4 }}
    {{- if eq .Values.ingress.tls.enabled true }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
spec:
  {{- if eq .Values.ingress.tls.enabled true }}
  tls:
    - hosts:
      - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.tls.secret }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.deployment.name }}
          servicePort: {{ .Values.service.internalPort }}